spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mkx_ranked
    username: mkx
    password: mkx

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

discord:
  token: ${DISCORD_TOKEN}